### PR TITLE
Migration to Gradle

### PR DESCRIPTION
**Pull request by lfoppiano**
I believe the migration to gradle works. The migration to dropwizard will be on a separate PR. 
We do now use gradle and gretty to run the jetty (or tomcat), moreover we now use jersey 2.x

### CODE REVIEW

**Comment by kermitt2** [comment]
Great !

However, `./gradlew runApp` is failing for me: 

```
lopez@work:~/grobid/grobid-astro$ ./gradlew runApp

FAILURE: Build failed with an exception.

* What went wrong:
Task 'runApp' not found in root project 'grobid-astro'.
```

**Comment by kermitt2** [comment]
After a new build, I have this:

```
lopez@work:~/grobid/grobid-astro$ ./gradlew clean install

> Task :mainJar
The SimpleWorkResult type has been deprecated and is scheduled to be removed in Gradle 5.0. Please use WorkResults.didWork() instead.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':install'.
> Could not publish configuration 'archives'
   > A POM can not have multiple main artifacts. Already have MavenArtifact grobid-astro:war:war:null, trying to add MavenArtifact grobid-astro:jar:jar:null
```

**Comment by lfoppiano** [comment]
Thanks @kermitt2 for testing. 
The first issue was the command, it's `appRun`, it's corrected in the last push 🌴 
The second issue is more related to the publication and now is not fully fixed (it doesn't generate the slim application jar) but it build correctly and it doesn't block the user to test it with gretty/jetty.

**Comment by kermitt2** [comment]
Thanks !

**Pull request merged**
